default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  prepared_statements: false
  advisory_locks: false
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: 127.0.0.1


development:
  <<: *default
  database: vulners_ruby_dev

production:
  <<: *default
  database: vulners_ruby_prod

test:
  <<: *default
  database: vulners_ruby_test